# Generated by Django 3.2.6 on 2022-07-24 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codehelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(max_length=64),
        ),
        migrations.RemoveField(
            model_name='list',
            name='category_id',
        ),
        migrations.AddField(
            model_name='list',
            name='category_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codehelp.category'),
        ),
        migrations.AlterField(
            model_name='list',
            name='description',
            field=models.TextField(max_length=1024),
        ),
    ]
