# Generated by Django 3.2.6 on 2022-07-27 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codehelp', '0002_auto_20220724_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='codehelp.category'),
        ),
    ]
